[pytest]
addopts =
    --cov=app
    --cov=pipeline
    --cov=routes
    --cov=models
    --cov=utils
    --cov=totw
    --cov-report=term-missing
    --cov-report=html
    --cov-fail-under=60
testpaths = tests
